//
//  DistrhoPluginInfo.h


#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND "Bram Giesen"
#define DISTRHO_PLUGIN_NAME  "LFO Blender"
#define DISTRHO_PLUGIN_URI   "http://bramgiesen.com/lfo-blender"

#define DISTRHO_PLUGIN_HAS_UI        0
#define DISTRHO_PLUGIN_IS_RT_SAFE    1

#define DISTRHO_PLUGIN_NUM_INPUTS    3
#define DISTRHO_PLUGIN_NUM_OUTPUTS   5

#define DISTRHO_PLUGIN_WANT_TIMEPOS  1
#define DISTRHO_PLUGIN_WANT_PROGRAMS 1

//#define DISTRHO_PLUGIN_LV2_CATEGORY "lv2:Plugin"

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
